<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220701013726 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('DROP TABLE contacts2');
        $this->addSql('DROP TABLE jounalistes_et_medias');
        $this->addSql('ALTER TABLE agence_de_communication_rp CHANGE representant representant VARCHAR(255) DEFAULT NULL, CHANGE fonction fonction VARCHAR(255) DEFAULT NULL, CHANGE telephone telephone VARCHAR(255) DEFAULT NULL, CHANGE mail mail VARCHAR(255) DEFAULT NULL, CHANGE adresse adresse VARCHAR(255) DEFAULT NULL, CHANGE agence_de_communication agence_de_communication VARCHAR(255) DEFAULT NULL, CHANGE adress1 adress1 VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE artistes_et_stylistes CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE Nom nom VARCHAR(255) DEFAULT NULL, CHANGE Domaine domaine VARCHAR(255) DEFAULT NULL, CHANGE Groupe groupe VARCHAR(255) DEFAULT NULL, CHANGE Pays_d_activite pays_d_activite VARCHAR(255) DEFAULT NULL, CHANGE Num num VARCHAR(255) DEFAULT NULL, CHANGE Email email VARCHAR(255) DEFAULT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE cinema_et_centre_cuturel ADD num_tel VARCHAR(255) DEFAULT NULL, DROP NumTel, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE Enseigne enseigne VARCHAR(255) DEFAULT NULL, CHANGE Contact contact VARCHAR(255) DEFAULT NULL, CHANGE Fonction fonction VARCHAR(255) DEFAULT NULL, CHANGE Adresse adresse VARCHAR(255) DEFAULT NULL, CHANGE Email email VARCHAR(255) DEFAULT NULL, CHANGE Commentaire commentaire VARCHAR(255) DEFAULT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE contacts ADD date DATE DEFAULT NULL, CHANGE commercial commercial VARCHAR(255) DEFAULT NULL, CHANGE client client VARCHAR(255) DEFAULT NULL, CHANGE contact contact VARCHAR(255) DEFAULT NULL, CHANGE poste poste VARCHAR(255) DEFAULT NULL, CHANGE ntel ntel VARCHAR(255) DEFAULT NULL, CHANGE nportable nportable VARCHAR(255) DEFAULT NULL, CHANGE email email VARCHAR(255) DEFAULT NULL, CHANGE commentaires commentaires VARCHAR(255) DEFAULT NULL, CHANGE etat etat VARCHAR(255) DEFAULT NULL');
        $this->addSql('DROP INDEX id ON cosmetique_et_parfum');
        $this->addSql('ALTER TABLE cosmetique_et_parfum CHANGE Enseigne enseigne VARCHAR(255) DEFAULT NULL, CHANGE Type type VARCHAR(255) DEFAULT NULL, CHANGE Gerant gerant VARCHAR(255) DEFAULT NULL, CHANGE Adresse adresse VARCHAR(255) DEFAULT NULL, CHANGE Num_Tel num_tel VARCHAR(255) DEFAULT NULL, CHANGE E_mail e_mail VARCHAR(255) DEFAULT NULL, CHANGE Commentaire commentaire VARCHAR(255) DEFAULT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('DROP INDEX id ON data_base_lm');
        $this->addSql('ALTER TABLE data_base_lm CHANGE Enseigne enseigne VARCHAR(255) DEFAULT NULL, CHANGE Type type VARCHAR(255) DEFAULT NULL, CHANGE Gerant gerant VARCHAR(255) DEFAULT NULL, CHANGE Adresse adresse VARCHAR(255) DEFAULT NULL, CHANGE Commune_Arrondissement commune_arrondissement VARCHAR(255) DEFAULT NULL, CHANGE Num_Tel num_tel VARCHAR(255) DEFAULT NULL, CHANGE Email email VARCHAR(255) DEFAULT NULL, CHANGE Commentaire commentaire VARCHAR(255) DEFAULT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('DROP INDEX id ON data_base_rpms');
        $this->addSql('ALTER TABLE data_base_rpms ADD agences_de_communication VARCHAR(255) DEFAULT NULL, ADD adresse2 VARCHAR(255) DEFAULT NULL, DROP Agences de communication, DROP `NULL`, CHANGE Representant representant VARCHAR(255) DEFAULT NULL, CHANGE Fonction fonction VARCHAR(255) DEFAULT NULL, CHANGE telephone telephone VARCHAR(255) DEFAULT NULL, CHANGE mail mail VARCHAR(255) DEFAULT NULL, CHANGE adresse adresse VARCHAR(255) DEFAULT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('DROP INDEX id ON data_fournisseurs_brut');
        $this->addSql('ALTER TABLE data_fournisseurs_brut CHANGE Enseigne enseigne VARCHAR(255) DEFAULT NULL, CHANGE Rubrique rubrique VARCHAR(255) DEFAULT NULL, CHANGE type type VARCHAR(255) DEFAULT NULL, CHANGE Gerant gerant VARCHAR(255) DEFAULT NULL, CHANGE Adresse adresse VARCHAR(255) DEFAULT NULL, CHANGE Commune_Arrondissement commune_arrondissement VARCHAR(255) DEFAULT NULL, CHANGE Num_tel num_tel VARCHAR(255) DEFAULT NULL, CHANGE Email email VARCHAR(255) DEFAULT NULL, CHANGE Lien_reseaux_sociaux_web lien_reseaux_sociaux_web VARCHAR(255) DEFAULT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('DROP INDEX id ON diplomatie');
        $this->addSql('ALTER TABLE diplomatie CHANGE Pays pays VARCHAR(255) DEFAULT NULL, CHANGE type type VARCHAR(255) DEFAULT NULL, CHANGE Representant representant VARCHAR(255) DEFAULT NULL, CHANGE Fonction fonction VARCHAR(255) DEFAULT NULL, CHANGE Telephone telephone VARCHAR(255) DEFAULT NULL, CHANGE e_Mail e_mail VARCHAR(255) DEFAULT NULL, CHANGE Adresse adresse VARCHAR(255) DEFAULT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('DROP INDEX id ON divertissement');
        $this->addSql('ALTER TABLE divertissement CHANGE Entreprise entreprise VARCHAR(255) DEFAULT NULL, CHANGE Personne personne VARCHAR(255) DEFAULT NULL, CHANGE Fonction fonction VARCHAR(255) DEFAULT NULL, CHANGE Numero numero VARCHAR(255) DEFAULT NULL, CHANGE Email email VARCHAR(255) DEFAULT NULL, CHANGE Adresse adresse VARCHAR(255) DEFAULT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('DROP INDEX id ON foodie');
        $this->addSql('ALTER TABLE foodie CHANGE Enseigne enseigne VARCHAR(255) DEFAULT NULL, CHANGE Type type VARCHAR(255) DEFAULT NULL, CHANGE Gerant gerant VARCHAR(255) DEFAULT NULL, CHANGE Adresse adresse VARCHAR(255) DEFAULT NULL, CHANGE Commune_Arrondissement_Ville commune_arrondissement_ville VARCHAR(255) DEFAULT NULL, CHANGE Num_Tel num_tel VARCHAR(255) DEFAULT NULL, CHANGE Email email VARCHAR(255) DEFAULT NULL, CHANGE Commentaire commentaire VARCHAR(255) DEFAULT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE fournisseurs CHANGE enseigne enseigne VARCHAR(255) DEFAULT NULL, CHANGE rubrique rubrique VARCHAR(255) DEFAULT NULL, CHANGE type type VARCHAR(255) DEFAULT NULL, CHANGE gerant gerant VARCHAR(255) DEFAULT NULL, CHANGE adresse adresse VARCHAR(255) DEFAULT NULL, CHANGE commune_arrondissement commune_arrondissement VARCHAR(255) DEFAULT NULL, CHANGE num_tel num_tel VARCHAR(255) DEFAULT NULL, CHANGE email email VARCHAR(255) DEFAULT NULL, CHANGE lien_reseaux_sociaux lien_reseaux_sociaux VARCHAR(255) DEFAULT NULL');
        $this->addSql('DROP INDEX id ON hotelerie_et_hebergement');
        $this->addSql('ALTER TABLE hotelerie_et_hebergement DROP `NULL`, CHANGE maison_d_hotes maison_d_hotes VARCHAR(255) DEFAULT NULL, CHANGE Type type VARCHAR(255) DEFAULT NULL, CHANGE Adresse adresse VARCHAR(255) DEFAULT NULL, CHANGE Commune_Arrondissement commune_arrondissement VARCHAR(255) DEFAULT NULL, CHANGE Num_Tel num_tel VARCHAR(255) DEFAULT NULL, CHANGE E_mail e_mail VARCHAR(255) DEFAULT NULL, CHANGE Nom nom VARCHAR(255) DEFAULT NULL, CHANGE Fonction fonction VARCHAR(255) DEFAULT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE journalistes_et_medias CHANGE media media VARCHAR(255) DEFAULT NULL, CHANGE personne personne VARCHAR(255) DEFAULT NULL, CHANGE fonction fonction VARCHAR(255) DEFAULT NULL, CHANGE numero numero VARCHAR(255) DEFAULT NULL, CHANGE email email VARCHAR(255) DEFAULT NULL, CHANGE adresse adresse VARCHAR(255) DEFAULT NULL');
        $this->addSql('DROP INDEX id ON shop_et_concept_store');
        $this->addSql('ALTER TABLE shop_et_concept_store CHANGE Enseigne enseigne VARCHAR(255) DEFAULT NULL, CHANGE Type type VARCHAR(255) DEFAULT NULL, CHANGE Gerant gerant VARCHAR(255) DEFAULT NULL, CHANGE Adresse adresse VARCHAR(255) DEFAULT NULL, CHANGE Commune_Arrondissement commune_arrondissement VARCHAR(255) DEFAULT NULL, CHANGE Num_Tel num_tel VARCHAR(255) DEFAULT NULL, CHANGE Email email VARCHAR(255) DEFAULT NULL, CHANGE Commentaire commentaire VARCHAR(255) DEFAULT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('DROP INDEX id ON textile_et_habillement');
        $this->addSql('ALTER TABLE textile_et_habillement CHANGE Enseigne enseigne VARCHAR(255) DEFAULT NULL, CHANGE Type type VARCHAR(255) DEFAULT NULL, CHANGE Createur createur VARCHAR(255) DEFAULT NULL, CHANGE E_mail e_mail VARCHAR(255) DEFAULT NULL, CHANGE Numero numero VARCHAR(255) DEFAULT NULL, CHANGE Adresse adresse VARCHAR(255) DEFAULT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE user CHANGE roles roles JSON DEFAULT NULL, CHANGE nom nom VARCHAR(255) DEFAULT NULL, CHANGE prenom prenom VARCHAR(255) DEFAULT NULL, CHANGE adress adress VARCHAR(255) DEFAULT NULL, CHANGE num_tel num_tel INT DEFAULT NULL, CHANGE poste poste VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE contacts2 (ID VARCHAR(104) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, COMMERCIAL VARCHAR(43) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CLIENT VARCHAR(56) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CONTACT VARCHAR(43) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, POSTE VARCHAR(59) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, NTEL VARCHAR(43) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, NPORTABLE VARCHAR(32) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, email VARCHAR(99) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, COMMENTAIRES VARCHAR(369) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, `NULL` VARCHAR(152) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('CREATE TABLE jounalistes_et_medias (id INT AUTO_INCREMENT NOT NULL, Media VARCHAR(57) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, Personne VARCHAR(24) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, Fonction VARCHAR(55) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, Numero VARCHAR(114) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, Email VARCHAR(90) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, Adresse VARCHAR(73) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, INDEX id (id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = MyISAM COMMENT = \'\' ');
        $this->addSql('ALTER TABLE agence_de_communication_rp CHANGE agence_de_communication agence_de_communication VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE representant representant VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE fonction fonction VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE telephone telephone VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE mail mail VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE adresse adresse VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE adress1 adress1 VARCHAR(255) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`');
        $this->addSql('ALTER TABLE artistes_et_stylistes MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE artistes_et_stylistes DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE artistes_et_stylistes CHANGE id id VARCHAR(28) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE nom Nom VARCHAR(148) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE domaine Domaine VARCHAR(81) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE groupe Groupe VARCHAR(46) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE pays_d_activite Pays_d_activite VARCHAR(76) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE num Num VARCHAR(52) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE email Email VARCHAR(53) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`');
        $this->addSql('ALTER TABLE cinema_et_centre_cuturel MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE cinema_et_centre_cuturel DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE cinema_et_centre_cuturel ADD NumTel VARCHAR(90) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, DROP num_tel, CHANGE id id VARCHAR(27) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE enseigne Enseigne VARCHAR(49) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE contact Contact VARCHAR(18) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE fonction Fonction VARCHAR(24) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE adresse Adresse VARCHAR(76) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE email Email VARCHAR(28) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE commentaire Commentaire VARCHAR(1) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`');
        $this->addSql('ALTER TABLE contacts DROP date, CHANGE commercial commercial VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE client client VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE contact contact VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE poste poste VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ntel ntel VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE nportable nportable VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE email email VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE commentaires commentaires VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE etat etat VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE cosmetique_et_parfum MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE cosmetique_et_parfum DROP INDEX primary, ADD INDEX id (id)');
        $this->addSql('ALTER TABLE cosmetique_et_parfum CHANGE enseigne Enseigne VARCHAR(49) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE type Type VARCHAR(15) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE gerant Gerant VARCHAR(21) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE adresse Adresse VARCHAR(98) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE num_tel Num_Tel VARCHAR(54) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE e_mail E_mail VARCHAR(37) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE commentaire Commentaire VARCHAR(1) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`');
        $this->addSql('ALTER TABLE data_base_lm MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE data_base_lm DROP INDEX primary, ADD INDEX id (id)');
        $this->addSql('ALTER TABLE data_base_lm CHANGE enseigne Enseigne VARCHAR(35) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE type Type VARCHAR(27) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE gerant Gerant VARCHAR(21) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE adresse Adresse VARCHAR(81) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE commune_arrondissement Commune_Arrondissement VARCHAR(9) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE num_tel Num_Tel VARCHAR(60) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE email Email VARCHAR(30) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE commentaire Commentaire VARCHAR(1) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`');
        $this->addSql('ALTER TABLE data_base_rpms MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE data_base_rpms DROP INDEX primary, ADD INDEX id (id)');
        $this->addSql('ALTER TABLE data_base_rpms ADD Agences de communication VARCHAR(33) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, ADD `NULL` VARCHAR(77) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, DROP agences_de_communication, DROP adresse2, CHANGE representant Representant VARCHAR(17) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE fonction Fonction VARCHAR(14) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE telephone telephone VARCHAR(58) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE mail mail VARCHAR(29) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE adresse adresse VARCHAR(108) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`');
        $this->addSql('ALTER TABLE data_fournisseurs_brut MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE data_fournisseurs_brut DROP INDEX primary, ADD INDEX id (id)');
        $this->addSql('ALTER TABLE data_fournisseurs_brut CHANGE enseigne Enseigne VARCHAR(30) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE rubrique Rubrique VARCHAR(35) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE type type VARCHAR(32) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE gerant Gerant VARCHAR(26) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE adresse Adresse VARCHAR(18) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE commune_arrondissement Commune_Arrondissement VARCHAR(86) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE num_tel Num_tel VARCHAR(36) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE email Email VARCHAR(33) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE lien_reseaux_sociaux_web Lien_reseaux_sociaux_web VARCHAR(93) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`');
        $this->addSql('ALTER TABLE diplomatie MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE diplomatie DROP INDEX primary, ADD INDEX id (id)');
        $this->addSql('ALTER TABLE diplomatie CHANGE pays Pays VARCHAR(51) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE type type VARCHAR(72) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE representant Representant VARCHAR(101) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE fonction Fonction VARCHAR(75) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE telephone Telephone VARCHAR(121) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE e_mail e_Mail VARCHAR(92) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE adresse Adresse VARCHAR(105) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`');
        $this->addSql('ALTER TABLE divertissement MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE divertissement DROP INDEX primary, ADD INDEX id (id)');
        $this->addSql('ALTER TABLE divertissement CHANGE entreprise Entreprise VARCHAR(47) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE personne Personne VARCHAR(27) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE fonction Fonction VARCHAR(46) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE numero Numero VARCHAR(56) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE email Email VARCHAR(36) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE adresse Adresse VARCHAR(83) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`');
        $this->addSql('ALTER TABLE foodie MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE foodie DROP INDEX primary, ADD INDEX id (id)');
        $this->addSql('ALTER TABLE foodie CHANGE enseigne Enseigne VARCHAR(51) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE type Type VARCHAR(22) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE gerant Gerant VARCHAR(61) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE adresse Adresse VARCHAR(231) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE commune_arrondissement_ville Commune_Arrondissement_Ville VARCHAR(17) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE num_tel Num_Tel VARCHAR(98) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE email Email VARCHAR(29) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE commentaire Commentaire VARCHAR(1) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`');
        $this->addSql('ALTER TABLE fournisseurs CHANGE enseigne enseigne VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE rubrique rubrique VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE type type VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE gerant gerant VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE adresse adresse VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE commune_arrondissement commune_arrondissement VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE num_tel num_tel VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE email email VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE lien_reseaux_sociaux lien_reseaux_sociaux VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE hotelerie_et_hebergement MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE hotelerie_et_hebergement DROP INDEX primary, ADD INDEX id (id)');
        $this->addSql('ALTER TABLE hotelerie_et_hebergement ADD `NULL` VARCHAR(1) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE maison_d_hotes maison_d_hotes VARCHAR(56) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE type Type VARCHAR(16) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE adresse Adresse VARCHAR(61) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE commune_arrondissement Commune_Arrondissement VARCHAR(45) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE num_tel Num_Tel VARCHAR(76) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE e_mail E_mail VARCHAR(40) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE nom Nom VARCHAR(32) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE fonction Fonction VARCHAR(18) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`');
        $this->addSql('ALTER TABLE journalistes_et_medias CHANGE media media VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE personne personne VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE fonction fonction VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE numero numero VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE email email VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE adresse adresse VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE shop_et_concept_store MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE shop_et_concept_store DROP INDEX primary, ADD INDEX id (id)');
        $this->addSql('ALTER TABLE shop_et_concept_store CHANGE enseigne Enseigne VARCHAR(35) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE type Type VARCHAR(28) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE gerant Gerant VARCHAR(23) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE adresse Adresse VARCHAR(82) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE commune_arrondissement Commune_Arrondissement VARCHAR(9) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE num_tel Num_Tel VARCHAR(60) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE email Email VARCHAR(30) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE commentaire Commentaire VARCHAR(1) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`');
        $this->addSql('ALTER TABLE textile_et_habillement MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE textile_et_habillement DROP INDEX primary, ADD INDEX id (id)');
        $this->addSql('ALTER TABLE textile_et_habillement CHANGE enseigne Enseigne VARCHAR(55) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE type Type VARCHAR(25) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE createur Createur VARCHAR(107) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE e_mail E_mail VARCHAR(31) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE numero Numero VARCHAR(87) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`, CHANGE adresse Adresse VARCHAR(108) CHARACTER SET utf8 DEFAULT \'NULL\' COLLATE `utf8_general_ci`');
        $this->addSql('ALTER TABLE user CHANGE roles roles LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE nom nom VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE prenom prenom VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE adress adress VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE num_tel num_tel INT DEFAULT NULL, CHANGE poste poste VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
    }
}
